---
- name: Install MySQL
  apt:
    name: "{{ mysql_packages }}"
    state: present

- name: Install PyMySQL dependency for Ansible MySQL modules
  apt:
    name: python3-pymysql
    state: present

- name: Start and enable MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Wait for MySQL socket
  wait_for:
    path: /var/run/mysqld/mysqld.sock
    state: present
    timeout: 30

- name: Set MySQL root password
  block:
    - name: Set MySQL root password (socket auth - fresh install)
      community.mysql.mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        login_user: root
        config_file: /dev/null
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true
        state: present
      register: mysql_root_set_socket
      failed_when: false
      changed_when: mysql_root_set_socket.rc == 0

    - name: Set MySQL root password using debian-sys-maint (Ubuntu/Debian - always available)
      shell: |
        mysql --defaults-file=/etc/mysql/debian.cnf <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';
        FLUSH PRIVILEGES;
        EOF
      when: mysql_root_set_socket.failed | default(false)
      no_log: true
      register: mysql_root_set_debian
      ignore_errors: yes

  rescue:
    - name: Set MySQL root password (using Ansible module with current password)
      community.mysql.mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        login_user: root
        login_password: "{{ mysql_root_current_password }}"
        config_file: /dev/null
        state: present
      when: mysql_root_current_password | length > 0
      ignore_errors: yes
      register: mysql_root_set_password

    - name: Fail if cannot set MySQL root password
      fail:
        msg: "Cannot set MySQL root password. All methods failed. If MySQL already has a password, set mysql_root_current_password in roles/database/defaults/main.yml to the current root password."
      when: >
        (mysql_root_set_socket.failed | default(true)) and
        (mysql_root_set_debian.failed | default(true)) and
        (mysql_root_set_password.failed | default(true))

- name: Create database
  community.mysql.mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    config_file: /dev/null
    check_implicit_admin: true

- name: Create database user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    config_file: /dev/null
    check_implicit_admin: true
