---
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Enable Apache service
  service:
    name: apache2
    enabled: yes
    state: started

- name: Enable PHP module in Apache
  command: a2enmod php
  notify: Restart Apache
