---
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Enable Apache service
  service:
    name: apache2
    enabled: yes
    state: started

- name: Configure Apache virtual host
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart Apache
